In [1]:
from __future__ import print_function
import torch

<img src="slide1.jpg">

<img src="firmen.png">

<img src="torch.png">

Usually one uses PyTorch either as:

    A replacement for numpy to use the power of GPUs.
    a deep learning research platform that provides maximum flexibility and speed


PyTorch is a python package that provides two high-level features:

- Tensor computation (like numpy) with strong GPU acceleration
- Deep Neural Networks built on a tape-based autodiff system

You can reuse your favorite python packages such as numpy, scipy and Cython to extend PyTorch when needed.

With PyTorch, we use a technique called Reverse-mode auto-differentiation, which allows you to change the way your network behaves arbitrarily with zero lag or overhead. Our inspiration comes from several research papers on this topic, as well as current and past work such as autograd, autograd, Chainer, etc.

<img src="graph.gif">


<img src="package.png">


If you use numpy, then you have used Tensors (a.k.a ndarray).

<img src="tensor_illustration.png">

PyTorch provides Tensors that can live either on the CPU or the GPU, and accelerate compute by a huge amount.

Broadcasting Regeln siehe: http://pytorch.org/docs/master/notes/broadcasting.html

Two tensors are “broadcastable” if the following rules hold:

- Each tensor has at least one dimension.
- When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.

# Tensoren

PyTorch Tensors verhalten sich sehr ähnlich wie numpy.ndarrays

torch.Tensor is an alias for the default tensor type (torch.FloatTensor).

In [2]:
x = torch.Tensor(5, 5)
print(x)

tensor(1.00000e-38 *
       [[ 8.5074,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])


In [3]:
x = torch.rand(5, 3)
print(x)


tensor([[ 0.8651,  0.7539,  0.0723],
        [ 0.7613,  0.0187,  0.1211],
        [ 0.1692,  0.0774,  0.2578],
        [ 0.0809,  0.6122,  0.1613],
        [ 0.1066,  0.1079,  0.4657]])


In [4]:
y = torch.rand(5,1)
print(y)

tensor([[ 0.9805],
        [ 0.8377],
        [ 0.8445],
        [ 0.6839],
        [ 0.3640]])


In [5]:
z = y * x 
print (z)

tensor([[ 0.8482,  0.7391,  0.0709],
        [ 0.6378,  0.0157,  0.1014],
        [ 0.1429,  0.0654,  0.2177],
        [ 0.0554,  0.4186,  0.1103],
        [ 0.0388,  0.0393,  0.1695]])


In [6]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a.pow(2)
print(a)

tensor([[ 1,  2,  3],
        [ 4,  5,  6]])


<img src="tensor.png">

In [7]:
tensor = torch.ones((2,), dtype=torch.int8)
data = [[0, 1], [2, 3]]
print(tensor.new_tensor(data))


tensor([[ 0,  1],
        [ 2,  3]], dtype=torch.int8)


# Autograd

- Automatische Ableitungen
- Keine Session - der Code bestimmt den Graphen (define-by-run)

## Variable

![](http://pytorch.org/tutorials/_images/Variable.png)

- Wrapper für Tensoren
- zentrale Schnittstelle zu pyTorch
- hält Methoden für die Bearbeitung der Gradienten


In [8]:
x = torch.autograd.Variable(torch.ones(2, 2), requires_grad=True)
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [9]:
f = x + 2
print(f)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


# Neuronale Netzwerke

- [```torch.nn```](http://pytorch.org/docs/master/nn.html)
- ```nn.Module```: 
    - Basisklasse aller Neuronalen Netzwerke
- ```nn.Parameter```: 
    - Ähnlich wie ```autograd.Variable```, registriert sich automatisch innerhalb einer von ```nn.Module``` erbenden Klasse
    - Alle definierten Parameter können über das Attribut ```net.parameters``` ausgegeben werden
- ```autograd.Function```: 
    - Implementierung der Vorwärts-Pfade im NN. 
    - Über die Registrierung von ```nn.Variable```  in F representiert diese mindestens 1 Knoten im Graphen des NN
    - Hier wird der Pfad und die Werte gespeichert um Backpropagation durchführen zu können.